#!/usr/bin/bash
#Initialize all that is necessary
#Download?
#TODO: Include message to confirm installing dependencies
sudo apt-get install python3
sudo apt-get install mariadb-server
sudo apt-get install libmariadb-dev
sudo apt-get install python3-pip
sudo apt-get install python3-tk
sudo apt install python3-matplotlib
sudo pip3 install mariadb
sudo pip3 install pandas
sudo pip3 install pandastable
#TODO: Include message to confirm resetting the database
#Initialize mariadb database 
echo Initializing the mariadb database...
sudo mariadb --verbose < init.sql
echo Complete!
#Initialize the last upload file
date --date="@0" +"%F %T" > ~/HEMS/home-server/backend/prevdatetime.txt
